<a href="https://colab.research.google.com/github/stefcian/Modern-Computer-Vision-with-PyTorch-2E/blob/main/Chapter01/Back_propagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from copy import deepcopy
import matplotlib.pyplot as plt
x = np.array([[1,1]])
y = np.array([[0]])

In [2]:
from copy import deepcopy
import numpy as np
def feed_forward(inputs, outputs, weights):
    pre_hidden = np.dot(inputs,weights[0])+ weights[1]
    print("\nhidden before activation = " + str(pre_hidden))
    hidden = 1/(1+np.exp(-pre_hidden))
    print("hidden after activation = " + str(hidden))
    out = np.dot(hidden, weights[2]) + weights[3]
    print("out value = " + str(out))
    mean_squared_error = np.mean(np.square(out - outputs))
    return mean_squared_error

In [3]:
def update_weights(inputs, outputs, weights, lr):
    original_weights = deepcopy(weights)
    temp_weights = deepcopy(weights)
    updated_weights = deepcopy(weights)
    original_loss = feed_forward(inputs, outputs, original_weights)
    for i, layer in enumerate(original_weights):
        for index, weight in np.ndenumerate(layer):
            temp_weights = deepcopy(weights)
            print("\ntemp_weights[" + str(i) + "][" + str(index) + "] = " + str(temp_weights[i][index]) + " before +0.0001 perturbation")
            temp_weights[i][index] += 0.0001
            print("temp_weights[" + str(i) + "][" + str(index) + "] = " + str(temp_weights[i][index]) + " after +0.0001 perturbation")
            _loss_plus = feed_forward(inputs, outputs, temp_weights)
            grad = (_loss_plus - original_loss)/(0.0001)
            updated_weights[i][index] -= grad*lr
            print("loss_plus = " + str(_loss_plus))
            print("loss_original = " + str(original_loss))
            print("grad = " + str(grad))
            print("lr = " + str(lr))
            print("updated_weights[" + str(i) + "][" + str(index) + "] = " + str(updated_weights[i][index]))
    return updated_weights, original_loss

In [4]:
W = [
    np.array([[-0.8, 0.2],
              [-0.4, -0.9],
              [-0.3, 0.5]], dtype=np.float32).T,
    np.array([-0.1, 0.5, -0.6], dtype=np.float32),
    np.array([[ 0.3, 0.5, 0.9]], dtype=np.float32).T,
    np.array([-0.5], dtype=np.float32)
]

In [5]:
losses = []
for epoch in range(1):
    W, loss = update_weights(x,y,W,0.01)
    losses.append(loss)
plt.plot(losses)
plt.title('Loss over increasing number of epochs')


hidden before activation = [[-0.70000001 -0.79999998 -0.40000004]]


NameError: name 'hidder' is not defined

In [ ]:
W

[array([[ 0.01424004, -0.5907864 , -0.27549535],
        [ 0.39883757, -0.52918637,  0.18640439]], dtype=float32),
 array([ 0.00554004,  0.5519136 , -0.06599568], dtype=float32),
 array([[ 0.3475135 ],
        [-0.05529078],
        [ 0.03760847]], dtype=float32),
 array([-0.22443289], dtype=float32)]

In [ ]:
pre_hidden = np.dot(x,W[0]) + W[1]
hidden = 1/(1+np.exp(-pre_hidden))
out = np.dot(hidden, W[2]) + W[3]

In [ ]:
out

array([[-0.0174781]])